### ISSUE TITLE
Additional mod material compatibility

### ISSUE THREAD

**Issue by bookerthegeek** [mickelus/tetra#143]
## Feature Request

**Feature description**
I would like for more materials from mods to be supported by default. The following for example:
- [ ] Thermal Expansion
- [ ] Nuclearcraft
- [ ] TechReborn
- [ ] Base Metals
- [ ] Modern Metals
- [ ] EnderIO
- [ ] Metallurgy 4
- [ ] Avaritia
- [ ] Blood Magic
- [ ] Botania
- [ ] ProjectRed
- [ ] Industrial Forgoing

**How it improves the player experience**
The ability to use more materials for tool parts would give the player more choice in how to use your mod. More choices is a good thing.

**Tetra synergies**
This aligns with current features in tetra by expanding on options already available to the the player.

**Comment by mickelus** [comment]
I need the following for each mod to implement this:

For each tool/weapon:
* name
* damage
* swing speed
* durability
* harvest capabilities (type, level, speed)
* effects (e.g. autosmelt or uses mana to restore durability, sweeping)
* usages (e.g. can till dirt or strip logs)

For each additional material:
 * applicable modules or slots (e.g. all blades or socket or all handles or handle wraps)
 * damage (fixed amount, or multiplier)
 * speed (fixed, multiplier)
 * durability
 * integrity
 * harvest capabilities (type, level, speed)
 * effects (e.g. autosmelt, uses mana to restore durability, sweeping)
 * usages (e.g. can till dirt or strip logs)

**Comment by NicholasRC7** [comment]
I can help with some of this:
All of the following can mine what iron can, unless otherwise stated.
Thermal:
(All of the following can be used wherever iron can)
Invar: Similar to iron, but slightly better in all stats
Bronze: Exactly Iron, but bronze colored
Electrum: More enchantable than gold, and about 4 times as durable. Similar to gold otherwise.
Constantan: Similar to copper, but slightly better overall stats, with lower speed
Platinum: Slightly better than diamond in all stats, can mine obsidian
Iridium: Max mining level, much better than diamond in all stats
Enderium: Same as platinum, slight chance to teleport enemies, always puts mined items directly in inventory
Steel: Similar to invar, but slightly better in all stats but speed, where it is slower.

NuclearCraft:
(All of these can be used wherever iron can)
Boron: High speed, low damage
Magnesium: Extreme speed, good integrity, but somewhat low durability. If the tool has blazing, it will be amplified. Bonus against undead mobs.
Tough Alloy: Poor stats, but extreme integrity. Can mine obsidian. Should be quite slow.
Hard carbon: Amazing speed and damage, but poor mining speed, very low integrity, very low durability, and can mine obsidian.
Uranium: High damage, high durability, but very slow speed. Tools made with it should give NuclearCraft radiation.
(This can be used wherever diamond can)
Boron Nitride: Amazing overall stats, extreme durability, good integrity, but low attack.
Botania:
Livingwood: Where wood can be used, has similar stats but gives the tool weak passive durability increase. Mild magic capacity.
Manasteel: Exact same stats as iron, but higher magic capacity and repairs with mana.
Elementium: Exact same stats as gold, but more durable and repairs with mana.
Terrasteel: Exact same stats as diamond, but repairs with mana and gives weak passive HP regen.
Socket: Mana Diamond: Discount on mana that is used for repairs
Binding: Mana-infused string: Increases integrity by 1, and increases magic capacity.

**Comment by mickelus** [comment]
That doesn't really help Nicholas, I was looking for actual values (e.g. the actual mining speed, mining level and durability of an invar pickaxe from thermal expansion). You've skipped out on several materials (e.g. copper, tin & lead from thermal expansion) and the stats you describe does not always align with how it works in that mod (or how it works in tetra). The table that NillerMedDild has provided in this issue https://github.com/mickelus/tetra/issues/145 is a good example of something that's helpful.

**Comment by mickelus** [comment]
Closing as this has been in need of refinement for a long time with no progress. Feel free to update & comment on the issue and I'll reopen it.

**Comment by Kirynn** [comment]
https://github.com/MinecraftModDevelopmentMods/MoarTinkers/blob/master/src/main/java/com/bartz24/moartinkers/registry/ModMaterials.java This seems to have a list of ALL materials, @mickelus if you could take a quick peek and let me know if this is the kind of data you're looking for and I'll format it nicely and add the extra data for you.
