### ISSUE TITLE
Modular shields

### ISSUE THREAD

**Issue by mickelus** [mickelus/tetra#151]
## Feature Discussion: Support for modular shields
Collection of suggestions and opinions regarding modular shields. I'm not well-versed when it comes to shield terminology, feel free to help out with that.

Interesting mechanics:
- [ ] Shield durability: Shields take damage based on how much damage is blocked (vanilla behaviour) and vanilla shields have 300-ish durability
- [ ] Durability damage reduction: Reduce the damage the shield takes by a flat or percentage amount, could be applied by padding the face of the shield
- [ ] Active durability damage reduction: When block is timed right shields don't take durability damage
- [ ] Partial block: Smaller shields could be limited to only partially block incoming damage, either by a flat amount or a percentage
- [ ] Max block amount: Shields stop blocking and go on cooldown when blocked damage exceeds a treshold, this would probably be ok to add to vanilla shields without ruining the vanilla experience
- [ ] Projectile deflection: When block is timed right shields could deflect incoming projectiles back at the attacker
- [ ] Parry/power block: When block is timed right shields could stun/disarm/debuff the attacker
- [ ] Max block duration: Limit the amount of time a shield can be held up, should go on cooldown afterwards. Vanilla has some remnants of this behaviour
- [ ] Shield bash: Click while holding shield to bash target. Can be upgraded with stuff like boosters to increase the range or spikes to increase damage.

Modules:
- [ ] Shield: major module, provides durability. Allows different shapes of shields such as tower, buckler, kite, heater. Trim would be an improvement for this rather than a module on it's own to allow different shapes. Padding / banner would be an improvement for this module.
- [ ] Handle: major module, provides integrity. 
- [ ] Shield boss: Shield bosses, spikes etc. Modules added here should add additional mechanics to the shield, preferrably that synergizes differently with different shield types.

**Comment by lag42** [comment]
would it be possible to do banners on these shields? obviously if so it should be lower on the list of priorities as it's a cosmetic only thing but i think that would still be a fun feature and make it more consistent with vanilla if the design conflicts with the different shield shapes don't completely scrap this idea

**Comment by Nerodon** [comment]
Most of your own ideas are pretty good for the most part but I think we can keep vanilla shield where is it and add more upon it.
Vanilla shield would be a typical light/medium shield

Here are some ideas I have to focus on:

***Shield Sizes*** 
Bigger shields could also take more time to lift up to block, so you need to lift in anticipation rather than reaction and make you slower when the shield is up (more so than vanilla) while lighter shields could be lifted as fast as vanilla (instantly) and allow you to run faster while blocking. For example, using a small shield such as a buckler, you'd be able to hold block without slowing down at all. The other difference could be block area, I'm not exactly sure even how vanilla calculates if youve been hit or not when holding a shield, but in theory, bigger shields, easier to block.

**Shield bash** 
Could be made interesting if say, instead of being like an attack, you actually need to be sprinting at the target and time a block right when you get near the target.
Think of it mechanically as, if your speed is over a certain amount (sprint) when you start blocking, it makes a knockback wave in front of you. This would deal some damage and create a knockback effect. The size and weight of the shield could increase the area of effect of the wave. Having a spike on the shield would deal more damage but with less pushback, and a piston mounted on the shield to deal no damage but push much further for example.  Also for the cherry on top, bashing an enemy would also push you back a little and allow some cool emergent strategies.

***Parry*** 
I do think timing your blocks should give some sort of parry effect, like stun or disarm, this would be very fun in PvP scenarios. I think an active effect like this is much more interesting than negating loss of durability. Say if you block right as the opponent attacks, that opponent gets an effect on them (maybe not just disarm, but a sort of stun where they can move but not attack for the duration of the effect, that way it works on most mobs too)

Just with the three above, then add durability and blocking area to the mix, you already have a good variance between light and heavy shields that are fundamentally different.

**Scenario 1:**
**Wooden Buckler**
- Does not slow you down when holding block
- Can parry enemies easily as blocking is instant
- Can bash enemies easily by sprinting then blocking when near but has low AoE, push and damage
- Low durability
- Harder to block attacks

**Scenario 2:**
**Iron Tower Shield**
- Very slow speed when holding block
- Tough to parry with because it takes longer to hold up
- Harder to bash because you need to time the ramp-up of the block as you sprint to the target but the effect is much bigger, more AoE, push, and damage.
- High durability
- Easier to block attacks
