### ISSUE TITLE
Extended reach only functions properly in creative mode

### ISSUE THREAD

**Issue by Ryminer2** [mickelus/tetra#210]
## Bug Report

**Observed Behaviour**
In survival or adventure mode, extended reach granted by held Tetra equipment only allows the player to target blocks at a further distance. Mobs and other entities disregard the extra range and can only be struck from the normal distance. Extended reach functions as expected in creative mode.

**Expected Behaviour**
Extended reach should function for entities as well as blocks outside of creative mode.

**Minimal setup needed to reproduce**
- Forge version: 1.15.2 - 31.2.36
- Tetra version: 2.18.1
- Tetra configuration: Default

**Steps to reproduce**
Use a weapon or tool that provides extended reach, such as a spear or a sword with a grip loop, in survival or adventure mode.

**Comment by mickelus** [comment]
As far as I'm aware this issue only applies for hitting entities, it works as expected for blocks. Have you noticed otherwise?

**Comment by VallenFrostweaver** [comment]
Forge: 35.1.7
Minecraft: 1.16.4
Tetra: 3.3.1
Can confirm this is accurate. It also isn't an accurate distance in creative either though as I am in the middle of the block I'm standing on. Target is in the middle of the block I'm attacking (target is the Dummy from the MmmMmmMmmMmm Dummy mod). I'm missing and there's 5 full blocks between the target's block and me and the spear I'm using says it hits at 7.4 blocks. So it's actually hitting at maybe 5.4 blocks due to hitbox size of the dummy. Tested with cows and it seems accurate too. It kinda invalidates the point of long handled spears with this only working in creative. Even more with less reach than advertised.

**Comment by mickelus** [comment]
Fixed in 3.6.1
