### ISSUE TITLE
[Suggestion] Invalid crafting items should be made more obvious

### ISSUE THREAD

**Issue by ejektaflex** [mickelus/tetra#22]
![tetra](https://user-images.githubusercontent.com/23628421/45352261-b3fc5c80-b57d-11e8-9c4a-ccf167754203.PNG)

Here's a small example. I feel like this is something that I should be able to do (downgrade an iron axe to a wooden hoe), but the create button is greyed out *even though stats change*, but no reason is given as to why. If a module can't use this material in this slot, it shouldn't show the stats of what the supposed material would calculate to (I think it's a bit misleading for new people). This has happened in a few situations, but this is one of the most basic examples. It would be nice to show a message in red saying why the item can't be made ("Invalid material") and such.

I love Tetra! Keep it up 👍

**Comment by mickelus** [comment]
It turns out that all materials that require any other tool than a hammer does not indicate this and vanilla items did not count as tools in this case. Stats are only intended to show up if it's a possible craft and if you lack the proper tool that should also show. This problem seem to have been around for a while, thanks for reporting the issue. Fix will be part of next release, and I'm happy that you like it!

**Comment by mickelus** [comment]
This has been fixed in  [0.15.1](https://minecraft.curseforge.com/projects/tetra/files/2616629).
