### ISSUE TITLE
Compatibility: Tetra's hammer can replace Immersive Engineering hammers

### ISSUE THREAD

**Issue by Edulml** [mickelus/tetra#224]
**Feature description**
Make the Tetra hammers be usable as the Engineer's Hammer for crafting metal plates and configuring machines. Given that one may craft with the hammer far more times than using it normally on the workbench, honing progress on crafting could be slowed down or even disabled to maintain the current pace for upgrading the tool. 

**How it improves the player experience**
It will allow players to carry one less redundant tool (both are hammers), making it a great quality of life feature.

**Tetra synergies**
It will give another use to the Hammer, an essential tool that normally (when inside a player's base) has no use outside the workbench.

**Comment by mickelus** [comment]
With how recipes work I don't think I can add support for this on my end. Tetra hammers provide the "hammer" tool type, you could ask the IE devs to change their recipe to check for that instead of a specific item. Or if they could check for an item tag in the recipe I could set it up so that modules add tags to the item (e.g. a hammer head would add the "forge:tools/hammer" tag to the item).

I could check with blu or malte when I find the time and energy to look into this.

**Comment by mickelus** [comment]
NBT sensitive item tags is not possible, I can't solve this on my end.
