### ISSUE TITLE
Cant obtain obsidian

### ISSUE THREAD

**Issue by Rarket-glitch** [mickelus/tetra#237]
## Bug Report

**Observed Behaviour**
When mining obsidian with a reforged pickaxe, no obsidian drops

**Expected Behaviour**
Obsidian would drop after mining with diamond pickaxe

**Minimal setup needed to reproduce**

- Forge version: 34.1.42
- Tetra version: 1.16.4
- Tetra configuration: Phantom membrane binding, flimsy handle, string wrap, diamond claw, mending enchant, and efficiency 5
- Other mods:

**Steps to reproduce**
Mine obsidian (created from lava source and water from water bucket (may not affect it though))

**Comment by Edulml** [comment]
Not a bug. Obsidian requires pickaxe level 4. Diamond pickaxe heads have mining level 3, and that gets upgraded to 4 when you make it a double headed diamond pickaxe. Since you have a diamond pick with a claw the mining level stays at 3.

Also here's a personal recommendation: I generally put an adze head on the other side of my pickaxe to have both pickaxe, competent shovel, and axe in one tool, and then put the claw on the other side of an axe.
