### ISSUE TITLE
[ISSUE] Resource Packs Useless

### ISSUE THREAD

**Issue by SeanChengN** [mickelus/tetra#24]
The Item ID is changed after craft, causing the resource packs useless.
**Image:**
![3](https://user-images.githubusercontent.com/20624068/45610214-ce5a9c80-ba8d-11e8-9fe0-6d386a0e5eb3.gif)
Is there a way to not affect the resource packs?

**Comment by mickelus** [comment]
Unfortunately tetra has to run its own item renderer, switching out different parts would otherwise yield no visual changes. You could use a resourcepack to change the textures in tetra, if you're interested in putting a pack together I can share the photoshop script I use for tinting and exporting different textures.

**Comment by SeanChengN** [comment]
Thank you for your reply, I am not good at using photoshop, so I can only wait for resource pack support oneday.

**Comment by Deshiba** [comment]
What resource pack are you using?

**Comment by SeanChengN** [comment]
> What resource pack are you using?

Conquest
https://www.planetminecraft.com/texture_pack/conquest-32x32/

**Comment by mickelus** [comment]
How did you make the gif?

**Comment by SeanChengN** [comment]
https://github.com/NickeManarin/ScreenToGif
