### ISSUE TITLE
Make GUI size scale with GUI size option

### ISSUE THREAD

**Issue by AngleWyrm10** [mickelus/tetra#263]
## Feature Request

Scale GUI larger/smaller according to player preference

**How it improves the player experience**
Current GUI presents text that is so small it's difficult to read.

Windows 10 recommended desktop resolution 1920x1080 screenshot
![Text size example](https://i.imgur.com/rzeXDwx.png)

**Comment by Moleculor** [comment]
I was _just_ asking about this on the Discord.

I play on GUI Scale 2, and yeah, the tiniest of text is several pt sizes smaller than the Minecraft text size when at that size.

Increasing the GUI scale in standard Video settings does increase the size of the holosphere UI (etc), but also (obviously) increases the size of the Minecraft UI, and the discrepancy remains present. (And the Tetra UI looks rather... blocky/ugly at that size, which is a shame for such a beautiful design.)

My eyes are old, ancient, and decaying. I'd love to be able to adjust the size of this UI independently of the GUI Scale setting in Minecraft.

**Comment by mickelus** [comment]
It scales with gui scale. If the gap between two scales is too large for your preference there's not much I can do for you. Perhaps there's a mod out there for you that allow more fine grained scaling :)

**Comment by Moleculor** [comment]
> If the gap between two scales is too large for your preference there's not much I can do for you. Perhaps there's a mod out there for you that allow more fine grained scaling :)

That really doesn't have anything to do with anything either of us have said?

Let me use pictures, since apparently words aren't conveying the problem.

![image](https://user-images.githubusercontent.com/3865976/103139525-bdecef80-46a2-11eb-899c-c459b00c4919.png)

This is all at the **same** GUI scale, **not** two **different** GUI scales.

See how the *mod's* text is a *fourth* of the size of Minecraft text? You can literally fit four letters in to the same space as one of Minecraft. 

All of the important *descriptive* and *explanatory* text is *tiny*. 

There is no text within vanilla Minecraft that is this small, and for good reason.

----

In passing, I *also* mentioned how, when scaled up to try and make the text readable, it doesn't scale well (it looks like it might be using nearest neighbor interpolation, maybe?).

![image](https://user-images.githubusercontent.com/3865976/103139585-5daa7d80-46a3-11eb-8ab1-38a272dec7ac.png)

But that was trying to describe how scaling up the GUI ruins the look of the text.
