### ISSUE TITLE
Repair material is inconsistent

### ISSUE THREAD

**Issue by MaskedBird** [mickelus/tetra#28]
I created a steel sword using IE steel. It tells me that it wants pulverized iron to repair it, which is from thermal foundation, and also iron. When I remove thermal foundation from my mod list entirely, it asks for a copper ingot to repair. How exactly is it calculating repair material?

**Comment by mickelus** [comment]
All parts of the sword have to be repaired, not just the blade. Each repair attempt will target a new part, which affect the repair amount and required materials. Variants using non-vanilla materials rely on the ore dictionary, the material for the steel blade correctly uses steelIngot from the oredict but it may be that iron dust from thermal foundation is incorrectly registered.

When looking into this I did however find that it only allows the first item matching the oredict entry.

I need more information in order to reproduce, please provide a minimal list of mods, tetra configuration and the list of parts used in the item which you're having repair issues with.

**Comment by MaskedBird** [comment]
RedstoneFlux-1.12-2.1.0.6-universal
CoFHCore-1.12.2-4.6.1.22-universal
CoFHWorld-1.12.2-1.3.0.6-universal
ThermalFoundation-1.12.2-2.6.1.22-universal

ImmersiveEngineering-0.12-86

tetra-1.12.2-0.19.0

Forge 14.23.5.2768

Thats the entire modlist.

Steps: create Iron pickaxe by normal minecraft crafting. use tetra crafting table to replace handle with oak planks. replace heads with steel from immersive engineering. Break a block. back in tetra table and repair.
Result: repair item will be pulverized iron. 
Next step: disable thermal foundations
Repeat above: repair item will be copper ingot.

**Comment by MaskedBird** [comment]
For some reason github won't let me edit the above post. 
Tetra configuration at default.
