### ISSUE TITLE
[ERROR] NullPointerException and RenderingBlockEntity

### ISSUE THREAD

**Issue by SakuraWuhen** [mickelus/tetra#343]
## Bug Report

**Observed Behaviour**

在进入某个峡谷时触发NullPointerException报错，
由于靠近便报错，我无法目击到底是什么方块引发了问题。
但它会严重影响游戏的继续进行，因为如果不删档便无法再次上线。

**Expected Behaviour**

NullPointerException：
https://gist.github.com/SakuraWuhen/a87abb4f27e53a1c70c6e2c0ab3e1273
and
Error executing task：
https://gist.github.com/SakuraWuhen/66e0befa6c86c801b39d04deaa61ce47
In addition to the null pointer, an error occurred. This error will not cause the inability to enter the game, but will cause rendering problems。

**Minimal setup needed to reproduce**

- Forge version: 1.12.2-14.23.5.2847
- Tetra version: 1.12.2-0.39.1
- Tetra configuration: default 

Hope these two error reports can help you solve the problem, if you need more information and feedback, I am willing to assist in the test

**Comment by mickelus** [comment]
There's a few issues with your issue:
* You've got several other mods present in your minecraft instance, try starting minecraft without the other mods and provide me with the logs if the issue persists
* Please fill out "Observed behaviour" and "Expected behaviour" correctly, I don't understand what "cause rendering problems" means (use google translate or ask someone to help you translate if you don't understand)
* I need the "Steps to reproduce" field to be able to look into the issue, you need to edit your issue and include that

**Comment by SakuraWuhen** [comment]
I'm sorry
This is indeed a problem with other modules
After careful investigation, I found that the root of the problem was the "dynamicResources" function of "VanillaFix" and
Conflict caused by the "Extractor piston" block of your mod

This function skips the loading of materials and models during the game startup phase, and changes to dynamic loading in the game.

Preventing the block from generating in the world will solve the problem

Sorry for my lack of rigor, and thank you for creating this excellent module
