### ISSUE TITLE
Allow Tetra Hoes to convert Farmer's Delight Rich Soil into Rich Soil Farmland

### ISSUE THREAD

**Issue by NillerMedDild** [mickelus/tetra#391]
## Feature Request

**Feature description**
Allow Tetra Hoes to convert Farmer's Delight `Rich Soil` into `Rich Soil Farmland`

**How it improves the player experience**
It allows the player to use one Hoe for all the things, instead of needing a vanilla hoe to convert 1 blocktype.

**Tetra synergies**
Yes.

**Comment by mickelus** [comment]
Wrote a super detailed response and then I turned off my browser, so here's a shorter response. Forge added [IForgeBlock.getToolModifiedState](https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/src/main/java/net/minecraftforge/common/extensions/IForgeBlockState.java#L795) in 1.16, from what I've understood this supersedes events such as UseHoeEvent.

Implementing `getToolModifiedState` in `RichSoilBlock` and making use of that to for the tilling interaction instead of the UseHoeEvent then it should work out of the box with tetra.

What do you think @vectorwing? (sorry for pinging you out of the blue)

**Comment by vectorwing** [comment]
Huh, good find! Seems they standardized the "block conversions" and it skipped my radar. I was actually thinking of consulting the tool type for "hoe", since 1.16 also added that, but this method might be more reliable.

I'll look into it. 👍

**Comment by vectorwing** [comment]
Update: it worked like a charm, and is a much more elegant solution. Should be up in the next version of Farmer's Delight. 👍

**Comment by vectorwing** [comment]
The change is now released on 0.4.1 on CurseForge. Feel free to close this issue.

**Comment by mickelus** [comment]
Oh, sweet!
