### ISSUE TITLE
[Mod Compat] Integration with Project: War Dance?

### ISSUE THREAD

**Issue by Corvus20** [mickelus/tetra#416]
## Feature Request

**Feature description**
Project: War Dance is a mod that adds more depth to combat, and is already compatible with a wide variety of mods. It is, however, unable to read in the stats of Tetra weapons (or weapons from any other modular equipment mod, such as tinkers or silent's gear) with some things being implemented on Tetra's end.

I had a chat with Project: War Dance's dev on this, and they say that there should be no rewrites needed, you just need to implement ICombatManipulator to get a lot of things going. I don't know all of the ins and outs of it, and would recommend you ask them for further details.

**How it improves the player experience**
The ability to use custom weapons from tetra in a combat enhancing mod like Project: War Dance would add so much more depth to combat. Plus, more compatibility is always a good thing.

**Tetra synergies**
In depth Weapon customization and more in depth combat go hand in hand in this instance. More compatibility is something that most modular equipment mods should strive for.

**Comment by mickelus** [comment]
It's really unclear to me what this would entail.

**Comment by Jackiecrazy** [comment]
A ping would have been nice...
I made a new item capability called [ICombatItemCapability](https://github.com/Jackiecrazy/WarDance/blob/master/src/main/java/jackiecrazy/wardance/capability/item/ICombatItemCapability.java). Any item that has this capability will use it to determine actions related to combat. You can modify damage or apply effects before or after armor calculations, on attack, and on parry or being parried, and it has a built in function for reducing x points of armor on a given attack because I use that often. I haven't looked deeply into Tetra code myself, but the request here seems to be adding appropriate defensive and offensive posture values based on NBT. I use an item-based registration in my config file, which can't handle NBT-based items.

**Comment by Corvus20** [comment]
Did anything ever come out of this?
