### ISSUE TITLE
Holosphere UI scroll function

### ISSUE THREAD

**Issue by lampshaded** [mickelus/tetra#423]
## Add functionality to the Holosphere UI to scroll through long lists of materials

**Feature description**
When you open up the Holosphere and view materials, if there are too many too fit on the screen, then the player can't view those which roll off of the screen. 

This is an issue, for example, if the player is using very many mods which add compatible materials. 

Functionality might be added to, say, click-and-drag, or use arrow keys, or click an on-screen arrow button to scroll through lists which are detected to exceed a certain length. 

If such functionality already exists, then perhaps this should be communicated more clearly to the player. After fiddling and searching online (and this git page) for tens of minutes, I couldn't personally find anything.

**How it improves the player experience**
This provides an in-game way for the player to view relevant material information which is otherwise buried inside of some json.

**Tetra synergies**
The Holosphere is already used for viewing materials, it just isn't able to do this in all scenarios.

**Comment by mickelus** [comment]
Use the scroll wheel. A visual indicator would probably not suffice for players that spend tens of minutes searching online instead of trying the scroll wheel :)

Won't fix for now.

**Comment by lampshaded** [comment]
I swear on my life that I thought I tried the scroll wheel!

Thanks for answering, and sorry for taking your time. Cheers.

**Comment by Twisted-Code** [comment]
Please consider reopening this issue for my sake. As we discussed on discord at one point, I physically cannot use a scroll wheel due to handicap-accessibility problems that make anything more complicated than a trackball... unwieldy. I came here to check if you were tracking my concern as an issue or not. Is it still a won't fix even after my explanations?
For now I'm going to see if I can work around my issue by using the source on this repo as documentation. The Holosphere's materials page is useless for me as is. Even if I can figure out where the data is on here, though, more accessible in-game-documentation would be greatly appreciated so I don't have to open a browser every time I need to check something. (Besides, such a workaround would be unable to make use of the GUI features for comparing materials automatically)
