### ISSUE TITLE
[Suggestion] Extra Block for Crafting Table

### ISSUE THREAD

**Issue by MasterEnderman** [mickelus/tetra#5]
Could you add the Crafting Table as an actual block? I'm making a modpack where the normal crafting table is acquired later in the game, but the player should have the possibility to start with tetra.

Really liking the mod so far. Looking forward to the next update. Keep up the good work!

**Comment by mickelus** [comment]
I'll add in the block item but without a recipe and add a config option to make it drop as its own item instead of dropping as a crafting table. Would that work out for you?

I'm glad that you like it, and thank you for the positivity! I've been working towards making all content configurable, it's been slow but it's almost done now!

**Comment by MasterEnderman** [comment]
That would be perfect. I'll add a recipe with CraftTweaker then. 👍

**Comment by mickelus** [comment]
Added workbench block and config option for making it drop itself rather than a crafting table in 0.11.0!
