### ISSUE TITLE
[Bug] Extractor crashes on completion without world corruption.

### ISSUE THREAD

**Issue by MsVella** [mickelus/tetra#551]
### Observed behaviour

When a hemmer is used to complete the extractor's initial hammering cycle and the ore generates the game flat crashes. This does not corrupt or otherwise damage the world and when it is restarted all of the ore has appeared around it, and it can be done again with the same result on subsequent hammerings.

### Expected behaviour

The extractor would work without a crash.

### Steps to reproduce

1. Place Extractor
2. Use it w/ T4 hammer
3. Crash
4. Profit

### Crashlog

https://gist.github.com/MsVella/7bf5e454f0eb013a9236c8a7ea32f6f0

### Tetra version

3.20.0

### mGui version

3.3.0

### Forge version

1.16.5 - 36.2.22

### Other mods

[Listed in the crash log, I'm not retyping all of them]

**Comment by mickelus** [comment]
This appears to be caused by darkerdepths which hooks into loot table behaviour, probably expecting a tool itemstack to be available even though there's no such loot parameter. I'm unable to find the source for that mod so I can't look into it any further, you'll have to create an issue on their tracker.

**Comment by MsVella** [comment]
Thanks
