### ISSUE TITLE
[Bug] Cannot craft tetra items

### ISSUE THREAD

**Issue by GObeynew** [mickelus/tetra#710]
### Observed behaviour

I cannot craft tetra items in survival. Technically the recipe exists, because when I use the creative menu, hover over the wooden mallet (example) and open the recipe with JEI its there, but when i try to search in jei or craft it, I cannot

### Expected behaviour

I should be able to craft tetra items.

### Steps to reproduce

1.Play on linked modpack
2. Try to craft items in survival

### Tetra version

4.10.1

### mutil/mGui version

4.5.0

### Forge version

1.18.2 - 40.2.0

### Other mods

[2023.zip](https://github.com/mickelus/tetra/files/11041743/2023.zip)

**Comment by GObeynew** [comment]
nwm

**Comment by mickelus** [comment]
Sorry bud, this is the wrong place to ask for help about changing the mod setup in atm7. Having someone create four identical issues in the issue tracker because they are unable to do something unrelated to the mod is not something I appreciate. I'm closing all of you issues, if you open another one you'll be blocked from further use of the issue tracker.
