### ISSUE TITLE
Bow doesnt draw from belt with quiver

### ISSUE THREAD

**Issue by chillcat222** [mickelus/tetra#73]
## Bug Report

**Observed Behaviour**

So i went into creative and fully upgraded the tool belt with a rabbit hide quiver but when i filled the quiver slots with arrows and went to draw the boy in survival no arrows would draw, i double checked to make sure i had the quiver part on, i did, and made double sure the slots had full arrows
**Expected Behaviour**

I expected the bow to use the arrows in the quiver but the only way i could use it was to use the keybind the take the arrows from the belt and put them in my offhand
**Minimal setup needed to reproduce**
  Tetra
  Baubles
- Forge version: 1.12.2 - 14.23.5.2847
- Other mods: 
- Tetra configuration: none, fresh install of the latest version 
**Steps to reproduce**

Get belt, add quiver, fill with arrows, put in belt bauble slot, get vanilla bow and try to shoot arrows

**Comment by mickelus** [comment]
Arrows are not supposed to draw automatically from the quiver, you need to apply the quick draw upgrade in order for it to behave like that. I tried this in 0.39.1 and it works as it's supposed to (although the supposed behaviour does not match your expected behaviour).

Closing this, feel free to reopen if you feel that it has been wrongfully closed.
