### ISSUE TITLE
[Bug] Hammer tier honing not calculating correctly when honing second time

### ISSUE THREAD

**Issue by thhn** [mickelus/tetra#795]
### Observed behaviour

When honing both head pieces on hammer to "Hammer tier" you get benefit only from first one

### Expected behaviour

When honing both head pieces with hammer tier upgrade total hammer tier should include improvement from both honings

### Steps to reproduce

1. Hone left hammer head to durability till lvl5
2. Hone left hammer head to hammer tier
3. Hone right hammer head to durability till lvl5
4. Hone right hammer head to hammer tier
5. Total hammer tier will not change when honing second time

### Tetra version

6.1.0

### mutil/mGui version

6.1.1

### Forge version

1.20.1 - 47.2.19

**Comment by Thebomb2d** [comment]
If you look at the advancements, it says that, among other things, double headed tool tier is calculated using only the head with the highest value. The hammer goes up a tier with the first hammer tier up hone because the head with the highest value went up a tier. The hammer tier didn't go up when you honed the second head because the head with the highest tier did not increase or change. Hope this helps.

**Comment by moonfather1** [comment]
while the explanation above makes sense, this is - at the very least - unfriendly user experience.
i would say *"oooh, one more tier, yes please"* and waste a hone and possibly an integrity point. everyone would.

the mod should warn in case of hones that add nothing, or hide them.

**Comment by mickelus** [comment]
Closing. Feel free to create a new issue if you're looking to propose a different way to convey how this works!
