### ISSUE TITLE
Compatibility with mystical world

### ISSUE THREAD

**Issue by mortghenn** [mickelus/tetra#87]
## Feature Request

**Feature description**
Usage of mystical world amethyst with tetra

**How it improves the player experience**
Amethyst provided by mystical world could be used for modifying tools with tetra

**Tetra synergies**
Tetra already has compatibility with the standard ingots added by mystical world (copper, tin, etc.), but it would be nice to have the amethyst as well to have a nice diamond alternative for tools.

**Comment by Edulml** [comment]
Another thing that could be added to the mystical world compatibility is their knives. You can already turn a sword into a modular knife, so it could be a nice little detail to turn its knifes into tetra's modular knifes and have tetra's knifes work with mystical world's crafting recipes if it can be done with this mod instead of having mystical world be the one doing the compatibility code.

**Comment by mickelus** [comment]
Amethyst is supported as a tool material. Closing as it's rather unclear what it's supposed to do as a socket.
